version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "teste"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vzfjphsmykgq"
s3_prefix = "teste"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "APIName=\"augmented_reality_back_end\""
image_repositories = []
